--EJECUTAR LA SIGUIENTE LINEA PARA CREAR LA BASE DE DATOS, NO SE DEBE EJECUTAR TODO EL ARCHIVO YA QUE GENERA ERROR
CREATE DATABASE DBAmadeus

--SELECCIONAR DESDE LA SIGUIENTE LA LINEA HASTA LA ULTIMA PARA EJECUTAR TODAS LAS INSTRUCCIONES SQL
USE DBAmadeus

IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'Employee' AND xtype = 'U')
BEGIN
CREATE TABLE Employee
(
[Id] INT IDENTITY(1,1) PRIMARY KEY
,[Name] VARCHAR(250)
,[Email] VARCHAR(250)
,[PhoneNumber] VARCHAR(10)
,[IsActive] BIT
,[DateCreated] DATE
)
END

IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'User' AND xtype = 'U')
BEGIN
CREATE TABLE [User]
(
[Id] INT IDENTITY(1,1) PRIMARY KEY
,[Email] VARCHAR(250)
,[Password] VARCHAR(MAX)
)
END

--select * from [User]
--select * from [Employee]
